name: Build App (Windows and Android)
on: [push]

jobs:
  # --- BUDOWANIE NA WINDOWS (.EXE) ---
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install flet==0.21.2 pyinstaller
      - name: Build EXE Manual
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "Organizator_Kryminalny" main.py
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Windows_App
          path: dist/*.exe

  # --- BUDOWANIE NA ANDROID (.APK) ---
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Flet
        run: |
          # Instalujemy konkretną, sprawdzoną wersję
          pip install flet==0.21.2
      - name: Build APK
        run: |
          # Usuwamy błędną flagę, flet build sam powinien wykryć moduły w tej wersji
          flet build apk
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android_App
          path: build/apk/*.apk
          
